name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  context_plus: ^4.1.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  provider: ^6.1.2
  provide_it: 
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
