name: provide_it_example
description: provide_it example app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  context_plus: ^4.1.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  provider: ^6.1.2
  provide_it: 
    path: ../
  riverpod: ^2.6.1
  performance: ^0.1.1
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
