name: provide_it
description: Provider-like state binding, management, and injection using only context extensions.
version: 0.7.0
homepage: https://www.branvier.com
repository: https://github.com/arthurbcd/provide_it
topics:
 - provider
 - context
 - state
 - management
 - injection

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
